### ISSUE TITLE
Revoking a signature from a hash

### ISSUE THREAD

**Issue by biern** [biern/signhash-poc#9]
I don't see why it shouldn't be possible. I don't think we've ever considered a use case like that, but there might be some we haven't thought of yet. @jstefanski what do you think?

**Comment by jksf** [comment]
I think this is crucial and with current implementation quite easy. As we don't have iterable proof methods we can easily delete key from proofs mapping.

This use case is significant for example when we lost some proof source (not paid for the domain) but have other valid proofs. We don't want to render to the user a huge warning that the hash is insecure because the http check on expired domain failed. This would leave the signer with no other option but changing address and registering again all hashes (huge PITA and cost).

Lack of this option would also be inconsistent with ability to override existing proofs with `addProof()` function.

**Comment by jksf** [comment]
Sorry, I misread it. I thought about revoking proof method.

**Comment by jksf** [comment]
I am thinking about the case when someone signs the file but later finds out it is invalid or malicious. It should be rare but we have no route to protect the users in this situation. I think that the signer should be able to revoke its signature on the file. What do you think @biern?

**Comment by biern** [comment]
I think the most important thing is that we agree that there's nothing fundamentally wrong with the fact of revoking a signature by a user. Your use cases are first that came to my mind too, they don't seem very common, but there's no point in blocking them. There might be more usages for that later on that we are not aware of yet. 
I'll add an issue to contracts to implement this.
